FROM --platform=$BUILDPLATFORM python:3.9-alpine3.15

RUN pip install --upgrade pip

RUN adduser -D tharuni
USER tharuni
WORKDIR /home/tharuni

ENV PATH="/home/tharuni/.local/bin:${PATH}"

COPY --chown=tharuni:tharuni requirements.txt requirements.txt
RUN pip install --user -r requirements.txt

COPY --chown=tharuni:tharuni . .

ENTRYPOINT ["python"]

CMD ["app.py"]
