apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo  
  template:
    metadata:
      labels:
        app: mongo  
    spec:
      containers:
        - image: mongo:latest
          name: mongo-cont
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db/
              name: todovol
      volumes:
        - name: todovol
          persistentVolumeClaim:
            claimName: todo-pvc
